### ISSUE TITLE
Assignment 3-4 - Tic-Tac-Toe

### ISSUE THREAD

**Issue by ambethia** [ESalvodon/Assignments#11]
## Explorer Mode

Make a 2 player tic-toe-toe game.
- [x] The game takes turns receiving input for each player.
- [x] The game recognizes when a player has won.
- [x] The board should be updated as it's state changes when people make moves.
- [x] If board is full before there is a winner, declare a tie.
- [x] Provide feedback for invalid moves (i.e. a player attempts to move in a space that's already filled).

Create an interface using CSS and Javascript. Use jQuery to handle events (e.g. when a player clicks on the game board) and to update the board.

Don't user `alert()` or `prompt()`! Use jQuery to update the page to indicate things to the user. Input should be by the user clicking.
## Adventure Mode

  Allow a single player to choose to play against the computer's "AI".
  Your AI might just make random moves at this point, or take a stab at making
  a smarter AI
## Epic Mode

  Your AI is unbeatable. The player will always lose or at best, tie. Yes, this is totally possible. Your game should also recognize a tie as soon as it becomes impossible to win.

**Comment by ESalvodon** [comment]
https://github.com/ESalvodon/Assignment-3-4---Tic-Tac-Toe

**Comment by ambethia** [comment]
Eddy, I couldn't get this to run.
