### ISSUE TITLE
Assignment 4-1 - jQuery TODOs

### ISSUE THREAD

**Issue by ambethia** [ESalvodon/Assignments#12]
### Description

Recreate the quintessential "TODO" list:

![](https://dl.dropboxusercontent.com/u/4024808/tiy/todos.png)
### Objectives
- Understand jQuery and DOM manipulation
- Understand HTML forms, inputs and their JS events
### Deliverables
- [x] a link to your source files, can be a Github repo or a Codepen.
- [x] a working, publicly visible website with a public URL (i.e. on Github Pages, or Codepen).
## Explorer Mode
- [x] Use jQuery
- [x] A form with a text input field to enter a task
- [x] When a task is added, append it to a list of tasks.
- [x] Tasks should be able to be marked as completed, this should change their visual appearance.
## Adventure Mode
- [ ] Add a filter (or tabs) to the TODO list to only show incomplete or completed items.
## Additional Resources & Documenation
- [MDN: HTML Forms Guide](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms)
- [jQuery API Docs](http://api.jquery.com)
- [jQuery Learning Center](https://learn.jquery.com)

**Comment by ESalvodon** [comment]
https://github.com/ESalvodon/Assignment-4-1---jQuery-TODOs
