### ISSUE TITLE
Assignment 5-1 - ES6 Videos

### ISSUE THREAD

**Issue by ambethia** [ESalvodon/Assignments#16]
A light one tonight.

Here's a couple videos to watch about ES6:
- https://www.youtube.com/watch?v=CozSF5abcTA
- https://www.youtube.com/watch?v=Hjkc9m9vYCU

Watch these, are write a short post in your blog about what _you_ think of the next version of JavaScript. Are you ready to start using it today (with Babel.js, etc)?

**Comment by ESalvodon** [comment]
https://medium.com/@esalvodon/javascript-the-next-generation-3b531f28880e
